### ISSUE TITLE
Build is broken with ffmpeg 9.0

### ISSUE THREAD

**Issue by bkuhls** [xbmc/inputstream.ffmpegdirect#381]
```
kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp: In member function 'void ffmpegdirect::FFmpegStream::ParsePacket(AVPacket*)':
kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp:1680:50: error: 'const struct AVCodecParser' has no member named 'parser_parse'
 1680 |         if (parser->second->m_parserCtx->parser->parser_parse)

kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp:1687:48: error: 'const struct AVCodecParser' has no member named 'parser_parse'
 1687 |           parser->second->m_parserCtx->parser->parser_parse(parser->second->m_parserCtx,

```
The now broken code was introduced by https://github.com/xbmc/inputstream.ffmpegdirect/commit/07ea26d7ce6bde1350ceb15380f4908da454f004

Upstream removed parser_parse with commit https://code.ffmpeg.org/FFmpeg/FFmpeg/commit/e967ae98f404aca912a80f014e6473276804235f

**Comment by phunkyfish** [comment]
@basilgello any idea on what we should do here instead?

**Comment by kel-mo** [comment]
kodi core hit this in the same function and moved to the public `av_parser_parse2()` in xbmc/xbmc@c4913a2 (the ffmpeg 8.1 bump), which might be what needs to happen here too? The code seems to have originated from there (07ea26d).
