### PR TITLE
Fix build against ffmpeg 9 by using av_parser_parse2()

### LINKED ISSUE #381: Build is broken with ffmpeg 9.0
```
kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp: In member function 'void ffmpegdirect::FFmpegStream::ParsePacket(AVPacket*)':
kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp:1680:50: error: 'const struct AVCodecParser' has no member named 'parser_parse'
 1680 |         if (parser->second->m_parserCtx->parser->parser_parse)

kodi-inputstream-ffmpegdirect-22.2.6-Piers/src/stream/FFmpegStream.cpp:1687:48: error: 'const struct AVCodecParser' has no member named 'parser_parse'
 1687 |           parser->second->m_parserCtx->parser->parser_parse(parser->second->m_parserCtx,

```
The now broken code was introduced by https://github.com/xbmc/inputstream.ffmpegdirect/commit/07ea26d7ce6bde1350ceb15380f4908da454f004

Upstream removed parser_parse with commit https://code.ffmpeg.org/FFmpeg/FFmpeg/commit/e967ae98f404aca912a80f014e6473276804235f

### PR DESCRIPTION
**Pull request by kel-mo**
ffmpeg 9 made `AVCodecParser::parser_parse` private, so the direct call in
`FFmpegStream::ParsePacket()` no longer compiles.

Kodi core hit this in the same function and moved to the public
`av_parser_parse2()` in xbmc/xbmc@c4913a2 (the ffmpeg 8.1 bump). This code came
from core originally (07ea26d), so this does the same here:

- drop the `if (parser->second->m_parserCtx->parser->parser_parse)` guard and
  check `m_codecCtx` in the outer `if` instead
- `const uint8_t* outbufptr` -> `uint8_t* outbufptr`
- call `av_parser_parse2()` and return early if it fails

`PARSER_FLAG_COMPLETE_FRAMES` stays set, so behaviour is unchanged. The result
matches core's current `CDVDDemuxFFmpeg::ParsePacket()`.

Builds and runs against ffmpeg 9.0.

Fixes #381

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by garbear** [comment]
Some CI still failing. Linux failing to link with libiconv? Win ARM64 didn't work before, we can disable that temporarily to not break the Jenkins release build.

**Comment by kel-mo** [comment]
LE and flatpak picked up the patch, and it is building on flatpak; I haven't looked into the CI here yet...

**Comment by garbear** [comment]
We should get this merged before B2 is released, likely this weekend. The CI failures don't affect Jenkins - see if you can fix them, but we can release even if they're still failing.

**Comment by garbear** [comment]
Jenkins is green, and that's what we care about, so I'll pull this in. Thanks for the fix!

**Comment by garbear** [comment]
I've released v22.2.7 with this fix.
